=== JCassio1/Broker-Web-Service/NetBeansProjects/BrokerWebService/conf/xml-resources/jaxb/shareSchema/Broker.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/Broker"
    xmlns:tns="http://xml.netbeans.org/schema/Broker"
    elementFormDefault="qualified">
    
    
    <!-- definition of complex elements -->
    
        <xsd:complexType name="Broker">
            <xsd:sequence>
                <xsd:element name="companyName" type="tns:StringLimit"/>
                <xsd:element name="companySymbol" type="tns:StringLimit"/>
                <xsd:element name="availableShares" type="tns:IntegerLimit"/>
                <xsd:element name="share_price" type="tns:share_price"/>
            </xsd:sequence>
        </xsd:complexType>
    
    
    <xsd:complexType name="share_price">
        <xsd:sequence>
            <xsd:element name="currency" type="tns:CurrencyLimit"/>
            <xsd:element name="value" type="tns:IntegerLimit"/>
            <xsd:element name="last-update" type="xsd:date"/>
        </xsd:sequence>
    </xsd:complexType>
    
    
    <!-- definition of list of shares -->
    
    <xsd:element name="Shares_Today">
        <xsd:complexType>
            <xsd:sequence >
                <xsd:element name="broker_collection" type="tns:Broker" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    
    
    <!-- definition of restrictions -->
    
    <xsd:simpleType name="StringLimit">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="15"></xsd:maxLength>
        </xsd:restriction>
    </xsd:simpleType>
    
    
    <xsd:simpleType name="IntegerLimit">
        <xsd:restriction base="xsd:int">
            <xsd:pattern value="[0-9]*"></xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>
    
    
    <xsd:simpleType name="CurrencyLimit">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="3"></xsd:maxLength>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== JCassio1/Broker-Web-Service/NetBeansProjects/Broker_service/src/broker_service/brokerXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ns1:Shares_Today
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://xml.netbeans.org/schema/Broker'
    xsi:schemaLocation='http://xml.netbeans.org/schema/Broker file:/Users/JCassio/NetBeansProjects/Broker_service/src/broker_service/Broker.xsd'>
    <ns1:broker_collection>
        <ns1:companyName>Joselson Inc.</ns1:companyName>
        <ns1:companySymbol>gcgcgccg</ns1:companySymbol>
        <ns1:availableShares>200</ns1:availableShares>
        <ns1:share_price>
            <ns1:currency>GBP</ns1:currency>
            <ns1:value>450</ns1:value>
            <ns1:last-update>2018-11-24</ns1:last-update>
        </ns1:share_price>
    </ns1:broker_collection>

</ns1:Shares_Today>
